### ISSUE TITLE
Create menu option that starts feature extraction

### ISSUE THREAD

**Issue by wbwakeman** [AllenInstitute/sweep_qc_tool#11]
- [x]  There is a `QAction` (probably on the edit menu?) that:
    - [x] starts feature extraction on the `FxData`
    - [x] brings up a "calculating, please wait" dialog
- [x] if extraction cannot be started (e.g. because the `PreFxData` is unset), a message is emitted instead.

**Comment by NileGraddis** [comment]
nice to have: status text indicating when fx is out of date

**Comment by sgratiy** [comment]
Increased estimate to 5 because we added status bar + status messaging
