### ISSUE TITLE
x-scaling for 'experiment epoch'

### ISSUE THREAD

**Issue by bergjim** [AllenInstitute/sweep_qc_tool#34]
I like that the x-scaling for the data traces in the 'experiment epoch' seems to be custom per stimulus type? For instance, you don't have the long baseline after the pulse. I have a couple questions on this - how is that scaling info being saved / implemented? It would be nice to modify the scaling for the Short Square pulses so the spike isn't so narrow. 2) I am a little worried about the x scaling missing the end of the data trace since one QC criteria is the cell returning to baseline. If that part of the display is truncated, the user may not know why the trace was auto_failed (or may not be able to evaluate it). One option would be to add a column with more of a 'raw' data trace, but that starts to be a lot of plots. Perhaps this is something we can discuss.

**Comment by NileGraddis** [comment]
Hi @bergjim,

The experiment epoch is extracted by [this code](https://github.com/AllenInstitute/ipfx/blob/b77da8b2cac12ee62585b2016c40e360cc6ec395/ipfx/epochs.py#L164), which looks for the 3rd (to account for test pulse) and last nonzero element of the current diff then pads by 1/2 seconds on each side.

Trying to find a one-size-fits all solution seems like it might not work out. What if instead we used pyqtgraph to implement user zooming/panning? Then the popup plots could support investigation of short- and long-timescale events. Example:
![pg_ex](https://user-images.githubusercontent.com/15089451/70839622-698e0f00-1dc2-11ea-952f-01e8e3137cf6.png)
